# Game Configuration  
[game]
max_turns = 2000
tick_rate = 0.001  # 1ms for headless
map_width = 20
map_height = 15
units_per_team = 6

[combat]
base_damage = 35.0
attack_range = 1

[units]
base_health = 100.0
movement_range = 1

[performance]
target_tps = 1000
enable_metrics = false  # Disable for performance
metrics_interval = 5.0
